version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuild_demo:latest .
      - docker tag codebuild_demo:latest public.ecr.aws/i8d1y6v9/codebuild_demo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/i8d1y6v9/codebuild_demo:latest
